import { Action } from 'redux'
// import axios from 'axios'
import { HeaderState } from '../main/headerMain'
// import { SearchAccountsResultObject } from '../model/types'
// import { AccountIdentifier } from '../../customer/model/types'
